#!/usr/bin/env python3
"""
grafana_provision.py — the ONLY sanctioned WRITE tool in this repo (Grafana-only).

Every other scripts/*.py is read-only and `prompt.md` Hard Rule #3 forbids mutating
Datadog/ES. This tool talks ONLY to Grafana (it reads InfluxDB/ES/Prometheus *through*
Grafana datasources — it never mutates them), so it does not touch that rule.

It provisions the curated SLO alert set (generated by gen_grafana_alerts.py from
kb/slo-catalog.json) into Grafana via the unified-alerting provisioning API, plus a
single #triage-bot-health Slack contact point. Design: references/architecture/alerting-system-design.md.

Auth (in priority order), from env:
  GRAFANA_TOKEN     service-account token  -> Authorization: Bearer  (RECOMMENDED)
  GRAFANA_USERNAME / GRAFANA_PASSWORD      -> form login at /login, cookie reused
GRAFANA_URL may be a login page (…/grafana/login); it is normalised and the API mount
point (root /api vs /grafana/api) is auto-detected against /api/health.

Subcommands (read-only unless noted):
  health                         connectivity + version
  datasources                    list name|type|uid
  contact-points                 list name|type
  rules                          list provisioned alert rules (title|uid|folder)
  probe                          resolve the catalog's needs_probe field names
                                   (SHOW MEASUREMENTS / SHOW FIELD KEYS / ES mapping / promql labels)
  contact-point-ensure   WRITE   create/update the triage-bot-health Slack contact point
  notification-policy-ensure WRITE update the routing tree for pager=triage-bot
  apply [--dry-run]      WRITE*   provision alerting/grafana/*.json into the SLO folder
                                   (--dry-run is the DEFAULT; pass --commit to actually write)
  test-fire --rule UID   WRITE    send a test notification to triage-bot-health

NEVER print GRAFANA_PASSWORD / token / cookies / webhook URLs.
"""
import argparse, json, os, sys, urllib.request, urllib.error, urllib.parse, http.cookiejar, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRAFANA_DIR = os.path.join(ROOT, "alerting", "grafana")
CATALOG = os.path.join(ROOT, "kb", "slo-catalog.json")


def normalise_url(raw):
    """Return (origin, mount_candidates). Strips /login and trailing slashes."""
    raw = (raw or "").strip().rstrip("/")
    for suffix in ("/login",):
        if raw.endswith(suffix):
            raw = raw[: -len(suffix)]
    p = urllib.parse.urlparse(raw)
    origin = f"{p.scheme}://{p.netloc}"
    path = p.path.rstrip("/")  # e.g. "/grafana" or ""
    # candidate API mount prefixes, most-specific first
    cands = []
    if path:
        cands.append(origin + path)
    cands.append(origin)
    # de-dup, keep order
    seen, out = set(), []
    for c in cands:
        if c not in seen:
            seen.add(c); out.append(c)
    return origin, out


class Grafana:
    def __init__(self, timeout=40):
        self.timeout = timeout
        self.token = os.environ.get("GRAFANA_TOKEN")
        self.user = os.environ.get("GRAFANA_USERNAME")
        self.pw = os.environ.get("GRAFANA_PASSWORD")
        self.origin, self.cands = normalise_url(os.environ.get("GRAFANA_URL"))
        self.cj = http.cookiejar.CookieJar()
        self.op = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(self.cj))
        self.prefix = None      # API mount prefix, e.g. https://host or https://host/grafana
        self._cookie_hdr = ""
        self._connect()

    def _raw(self, url, data=None, headers=None, method=None):
        req = urllib.request.Request(url, data=data, method=method)
        for k, v in (headers or {}).items():
            req.add_header(k, v)
        if self.token:
            req.add_header("Authorization", "Bearer " + self.token)
        elif self._cookie_hdr:
            req.add_header("Cookie", self._cookie_hdr)
        last = None
        for _ in range(3):
            try:
                r = self.op.open(req, timeout=self.timeout)
                return r.status, r.read().decode()
            except urllib.error.HTTPError as e:
                return e.code, e.read().decode()
            except Exception as e:
                last = e; time.sleep(2)
        raise SystemExit(f"network error talking to Grafana: {last!r} "
                         f"(is it up? GRAFANA_URL={self.origin}…)")

    def _connect(self):
        # session login first (if no token) so the cookie exists for mount detection
        if not self.token:
            if not (self.user and self.pw):
                raise SystemExit("set GRAFANA_TOKEN, or GRAFANA_USERNAME+GRAFANA_PASSWORD")
            body = json.dumps({"user": self.user, "password": self.pw}).encode()
            # login endpoint: try each candidate's /login, then origin/login
            for c in self.cands + [self.origin]:
                st, _ = self._raw(c + "/login", data=body, headers={"Content-Type": "application/json"})
                if st == 200:
                    break
            self._cookie_hdr = "; ".join(f"{ck.name}={ck.value}" for ck in self.cj)
        # detect API mount via /api/health
        for c in self.cands:
            st, txt = self._raw(c + "/api/health")
            if st == 200 and txt.lstrip().startswith("{") and "database" in txt:
                self.prefix = c
                return
        raise SystemExit(f"could not locate Grafana API under any of {self.cands} "
                         f"(/api/health did not return health JSON — instance down?)")

    def api(self, path, data=None, method=None):
        body = json.dumps(data).encode() if data is not None else None
        hdr = {"Content-Type": "application/json"} if data is not None else {}
        st, txt = self._raw(self.prefix + path, data=body, headers=hdr, method=method)
        return st, txt

    def jget(self, path):
        st, txt = self.api(path)
        if st != 200:
            raise SystemExit(f"GET {path} -> {st}: {txt[:200]}")
        return json.loads(txt)


# ---------- read-only commands ----------
def cmd_health(g, a):
    print(json.dumps(g.jget("/api/health")), "\nAPI mount:", g.prefix)

def cmd_datasources(g, a):
    for d in sorted(g.jget("/api/datasources"), key=lambda x: x["name"]):
        print(f"  {d['name']:30} | {d['type']:14} | uid={d['uid']}")

def cmd_contact_points(g, a):
    for c in g.jget("/api/v1/provisioning/contact-points"):
        print(f"  {c.get('name'):30} | {c.get('type')}")

def cmd_rules(g, a):
    for r in g.jget("/api/v1/provisioning/alert-rules"):
        print(f"  {r.get('title','')[:55]:55} | uid={r.get('uid')} | folder={r.get('folderUID')}")

def _ds_by_name(g):
    return {d["name"]: d for d in g.jget("/api/datasources")}

def cmd_probe(g, a):
    """Resolve needs_probe field names referenced by the catalog."""
    cat = json.load(open(CATALOG, encoding="utf-8"))
    ds = _ds_by_name(g)
    for slo in cat["slos"]:
        if not slo.get("needs_probe"):
            continue
        print(f"\n=== {slo['id']} {slo['journey']} ({slo.get('build_status')}) ===")
        print("  probe_note:", slo.get("probe_note"))
        d = slo.get("datasource", {})
        name = d.get("metric")
        if name and name in ds and ds[name]["type"] == "influxdb":
            uid = ds[name]["uid"]
            dbname = ds[name].get("database") or (ds[name].get("jsonData") or {}).get("dbName") or ""
            qs = urllib.parse.urlencode({"db": dbname, "q": "SHOW MEASUREMENTS"})
            st, txt = g.api(f"/api/datasources/proxy/uid/{uid}/query?{qs}")
            print(f"  {name} (db={dbname}) SHOW MEASUREMENTS -> {st}")
            if st == 200:
                try:
                    vals = json.loads(txt)["results"][0].get("series", [{}])[0].get("values", [])
                    print("    measurements:", ", ".join(v[0] for v in vals[:40]))
                except Exception as ex:
                    print("    parse:", ex, txt[:150])
            else:
                print("   ", txt[:150])
        elif name:
            print(f"  metric datasource '{name}': type={ds.get(name,{}).get('type','MISSING')} — inspect manually")


# ---------- write commands ----------
def cmd_contact_point_ensure(g, a):
    webhook = os.environ.get("TRIAGE_BOT_HEALTH_WEBHOOK")  # never committed
    spec = json.load(open(os.path.join(GRAFANA_DIR, "_contact-point.json"), encoding="utf-8"))
    name = spec["name"]
    settings = {"recipient": "#triage-bot-health", "text": spec["message_template"]}
    if webhook:
        settings["url"] = webhook  # incoming-webhook style; token-style would use 'token'
    payload = {"name": name, "type": "slack", "settings": settings, "disableResolveMessage": False}
    existing = {c["name"]: c for c in g.jget("/api/v1/provisioning/contact-points")}
    if not a.commit:
        print(f"[dry-run] would {'update' if name in existing else 'CREATE'} Slack contact point '{name}' "
              f"-> #triage-bot-health (no @-mentions). Pass --commit to apply.")
        if not webhook:
            print("  note: set TRIAGE_BOT_HEALTH_WEBHOOK in env to supply the webhook (kept out of the repo).")
        return
    if not webhook:
        raise SystemExit("refusing to create contact point without TRIAGE_BOT_HEALTH_WEBHOOK in env")
    if name in existing:
        st, txt = g.api(f"/api/v1/provisioning/contact-points/{existing[name]['uid']}", data=payload, method="PUT")
    else:
        st, txt = g.api("/api/v1/provisioning/contact-points", data=payload, method="POST")
    print(f"contact-point '{name}' -> {st} {txt[:120]}")


def _ensure_folder(g, title, commit):
    for f in g.jget("/api/folders"):
        if f["title"] == title:
            return f["uid"]
    if not commit:
        return None
    st, txt = g.api("/api/folders", data={"title": title}, method="POST")
    if st not in (200, 412):
        raise SystemExit(f"create folder '{title}' -> {st}: {txt[:150]}")
    return json.loads(txt)["uid"]


def cmd_apply(g, a):
    cat = json.load(open(CATALOG, encoding="utf-8"))
    folder_title = cat["meta"]["grafana_folder"]
    ds = _ds_by_name(g)
    folder_uid = _ensure_folder(g, folder_title, a.commit)
    existing = {r["uid"]: r for r in g.jget("/api/v1/provisioning/alert-rules")}
    n_create = n_update = n_skip = 0
    for fn in sorted(os.listdir(GRAFANA_DIR)):
        if fn.startswith("_") or not fn.endswith(".json"):
            continue
        obj = json.load(open(os.path.join(GRAFANA_DIR, fn), encoding="utf-8"))
        for rule in obj.get("rules", []):
            # resolve datasource NAMES -> uids (leave __expr__ alone)
            unresolved = []
            for q in rule["data"]:
                u = q.get("datasourceUid")
                if u and u != "__expr__":
                    if u in ds:
                        q["datasourceUid"] = ds[u]["uid"]
                    elif u not in {d["uid"] for d in ds.values()}:
                        unresolved.append(u)
            rule["folderUID"] = folder_uid
            action = "update" if rule["uid"] in existing else "CREATE"
            warn = f"  ⚠ unresolved datasource(s): {unresolved}" if unresolved else ""
            probe = "  [needs_probe]" if obj.get("needs_probe") else ""
            if not a.commit:
                print(f"[dry-run] {action:6} {rule['uid']:28} '{rule['title'][:48]}'{probe}{warn}")
                n_create += action == "CREATE"; n_update += action == "update"
                continue
            if unresolved:
                print(f"SKIP {rule['uid']} — unresolved datasource {unresolved} (run probe / fix catalog)")
                n_skip += 1; continue
            if action == "CREATE":
                st, txt = g.api("/api/v1/provisioning/alert-rules", data=rule, method="POST")
            else:
                st, txt = g.api(f"/api/v1/provisioning/alert-rules/{rule['uid']}", data=rule, method="PUT")
            ok = st in (200, 201)
            print(f"{action} {rule['uid']} -> {st}" + ("" if ok else f" {txt[:160]}"))
            n_create += ok and action == "CREATE"; n_update += ok and action == "update"
    mode = "DRY-RUN (nothing written — pass --commit to apply)" if not a.commit else "COMMITTED"
    print(f"\n{mode}: folder='{folder_title}' (uid={folder_uid}) create={n_create} update={n_update} skip={n_skip}")


def cmd_test_fire(g, a):
    spec = json.load(open(os.path.join(GRAFANA_DIR, "_contact-point.json"), encoding="utf-8"))
    name = spec["name"]
    webhook = os.environ.get("TRIAGE_BOT_HEALTH_WEBHOOK")
    if not a.commit:
        print(f"[dry-run] would send a Grafana test notification to contact point '{name}' (#triage-bot-health). Pass --commit.")
        return
    if not webhook:
        raise SystemExit("TRIAGE_BOT_HEALTH_WEBHOOK not in env — needed to test the slack receiver config")
    # Grafana 'test receiver' API: send a sample alert through the named contact point.
    body = {
        "receivers": [{
            "name": name,
            "grafana_managed_receiver_configs": [{
                "name": name, "type": "slack", "disableResolveMessage": False,
                "settings": {"recipient": "#triage-bot-health", "url": webhook, "text": spec["message_template"]},
            }],
        }],
        "alert": {
            "annotations": {"summary": "triage-bot SLO alerting — Grafana test-fire (owner: DevOps, inert text)"},
            "labels": {"slo": "TEST", "severity": "P3", "owner": "DevOps", "pager": "triage-bot"},
        },
    }
    st, txt = g.api("/api/alertmanager/grafana/config/api/v1/receivers/test", data=body, method="POST")
    print(f"test-fire -> {st} {txt[:200] or '(empty = sent)'}")


COMMANDS = {
    "health": cmd_health, "datasources": cmd_datasources, "contact-points": cmd_contact_points,
    "rules": cmd_rules, "probe": cmd_probe, "contact-point-ensure": cmd_contact_point_ensure,
    "notification-policy-ensure": cmd_contact_point_ensure,  # policy bundled with contact-point spec
    "apply": cmd_apply, "test-fire": cmd_test_fire,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=list(COMMANDS))
    ap.add_argument("--commit", action="store_true", help="actually write (default is dry-run for write cmds)")
    ap.add_argument("--rule", help="rule uid for test-fire")
    ap.add_argument("--no-connect", action="store_true", help="(self-test) skip connecting to Grafana")
    a = ap.parse_args()
    if a.no_connect:
        print("self-test: argparse OK, command =", a.command)
        return
    g = Grafana()
    COMMANDS[a.command](g, a)


if __name__ == "__main__":
    main()
